// <auto-generated />
using System;
using API_Manajemen_Layanan_Pesan_Antar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Manajemen_Layanan_Pesan_Antar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524115808_add_table")]
    partial class add_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.Order", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("cancel_remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("canceled_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("cash_amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cust_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cust_phone_number")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("delivered_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delivered_by")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("order_number")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("order_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("received_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("suspend_remark")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("suspended_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("total_payment")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.OrderDelivery", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal?>("courier_latitude")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal?>("courier_longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("delivery_address")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("delivery_latitude")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("delivery_longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("delivery_remark")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("location_name")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.ToTable("OrderDelivery");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.OrderItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("order_id")
                        .HasColumnType("bigint");

                    b.Property<int>("order_qty")
                        .HasColumnType("int");

                    b.Property<long>("product_id")
                        .HasColumnType("bigint");

                    b.Property<int>("subtotal")
                        .HasColumnType("int");

                    b.Property<int>("unit_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.Product", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("available_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("product_desc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("unit_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.OrderDelivery", b =>
                {
                    b.HasOne("API_Manajemen_Layanan_Pesan_Antar.Models.Order", null)
                        .WithOne("order_delivery")
                        .HasForeignKey("API_Manajemen_Layanan_Pesan_Antar.Models.OrderDelivery", "order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.OrderItem", b =>
                {
                    b.HasOne("API_Manajemen_Layanan_Pesan_Antar.Models.Order", null)
                        .WithMany("order_items")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Manajemen_Layanan_Pesan_Antar.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("API_Manajemen_Layanan_Pesan_Antar.Models.Order", b =>
                {
                    b.Navigation("order_delivery")
                        .IsRequired();

                    b.Navigation("order_items");
                });
#pragma warning restore 612, 618
        }
    }
}
